//Configuration for Control Panel
//Automatically Generated by PhantomBot at Startup
//Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 25004,
    channelName : "sqee03",
    auth        : "gQgivKPatVnCdRd0S4yY5uqfTMpX9x",
    http        : "http://"
};

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
